pages:
  stage: deploy
  script:
  - mkdir -p /var/www/site/app
  - nice jekyll build --incremental -d /var/www/site/app
  - sshpass -p $SSHPASS ssh tlo@localhost "cd $PWD; git push --force --mirror git@github.com:TLOxyz/APP.git ;"
  only:
  - master